# Generated by Django 6.1.1 on 2026-10-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_photo_url_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('pix', 'PIX')], max_length=20, null=True),
        ),
    ]
